Vagrant.configure("2") do |config|

  config.vm.define "docker" do |docker|
    docker.vm.hostname = "docker"
    docker.vm.box = "ubuntu/trusty64"

    docker.vm.provision :shell, path: "bootstrap.sh"

    docker.vm.network "forwarded_port", guest: 9200, host: 9200
    docker.vm.network "forwarded_port", guest: 9292, host: 9292
    docker.vm.network "forwarded_port", guest: 12200, host: 12200
    docker.vm.network "forwarded_port", guest: 12200, host: 12200, protocol: "udp"
  end
  config.vm.provider "virtualbox" do |docker|
    docker.memory = 2048
  end
end
